### ISSUE TITLE
Basic Server with file upload

### ISSUE THREAD

**Issue by jwildfire** [RhoInc/volcano-plot#10]
Add a basic server that can accept uploaded datasets and settings objects and provide API calls to retrieve both to plug into the renderer.

**Comment by rbudrevich** [comment]
To get up and running:

Cmdline:
npm install
npm run rebuild-db
npm run build-server

Browser: 
http://localhost:8888/client/upload.html (upload file and config, rest of fields arbitrary)
There's an id 1 preloaded in the db, so the first upload should create id 2. API calls:
http://localhost:8888/api/datasets/2 (metadata you uploaded)
http://localhost:8888/api/datasets/2/data.json (your uploaded file converted to json)

From there you can edit client/index.html, set id =2 and load http://localhost:8888/client/, and should see it render.
